// Code generated by protoc-gen-go-baseconvert. DO NOT EDIT.

package subpackage

import (
	subpackage "github.com/devnev/proto-releases/fixtures/subpackage"
)

func (m *ImportedNotAnnotatedAndEmpty) ToBase() *subpackage.ImportedNotAnnotatedAndEmpty {
	msg := &subpackage.ImportedNotAnnotatedAndEmpty{}
	return msg
}
func (m *ImportedNotAnnotatedAndEmpty) FromBase(b *subpackage.ImportedNotAnnotatedAndEmpty) *ImportedNotAnnotatedAndEmpty {
	msg := &ImportedNotAnnotatedAndEmpty{}
	return msg
}
func (m *ImportedNotAnnotatedWithUnreleasedField) ToBase() *subpackage.ImportedNotAnnotatedWithUnreleasedField {
	msg := &subpackage.ImportedNotAnnotatedWithUnreleasedField{
		Released: m.GetReleased(),
	}
	return msg
}
func (m *ImportedNotAnnotatedWithUnreleasedField) FromBase(b *subpackage.ImportedNotAnnotatedWithUnreleasedField) *ImportedNotAnnotatedWithUnreleasedField {
	msg := &ImportedNotAnnotatedWithUnreleasedField{
		Released: b.GetReleased(),
	}
	return msg
}
func (m *ImportedNotAnnotatedWithReleasedField) ToBase() *subpackage.ImportedNotAnnotatedWithReleasedField {
	msg := &subpackage.ImportedNotAnnotatedWithReleasedField{
		Released: m.GetReleased(),
	}
	return msg
}
func (m *ImportedNotAnnotatedWithReleasedField) FromBase(b *subpackage.ImportedNotAnnotatedWithReleasedField) *ImportedNotAnnotatedWithReleasedField {
	msg := &ImportedNotAnnotatedWithReleasedField{
		Released: b.GetReleased(),
	}
	return msg
}
