// Code generated by protoc-gen-baseconvert. DO NOT EDIT.

package testdata

import (
	golden "github.com/devnev/proto-releases/testdata/golden"
)

func (m *EmptyRootMessageReleased) ToBase() *golden.EmptyRootMessageReleased {
	return &golden.EmptyRootMessageReleased{}
}
func (m *EmptyRootMessageReleased) FromBase(b *golden.EmptyRootMessageReleased) {
	m.Reset()
}
func (m *EmptyRootMessageReleasedThenRemoved) ToBase() *golden.EmptyRootMessageReleasedThenRemoved {
	return &golden.EmptyRootMessageReleasedThenRemoved{}
}
func (m *EmptyRootMessageReleasedThenRemoved) FromBase(b *golden.EmptyRootMessageReleasedThenRemoved) {
	m.Reset()
}
func (m *RootMessageNotAnnotated) ToBase() *golden.RootMessageNotAnnotated {
	return &golden.RootMessageNotAnnotated{
		Released:            m.GetReleased(),
		ReleasedThenRemoved: m.GetReleasedThenRemoved(),
	}
}
func (m *RootMessageNotAnnotated) FromBase(b *golden.RootMessageNotAnnotated) {
	m.Reset()
	m.Released = b.GetReleased()
	m.ReleasedThenRemoved = b.GetReleasedThenRemoved()
}
