// Code generated by protoc-gen-go-torelease. DO NOT EDIT.

package examples

import (
	proto_releases "github.com/devnev/proto-releases"
)

func (m *Example) ToRelease(c *proto_releases.Config) {
	if m == nil || c.GetRelease() == 0 {
		return
	}
	r, p := c.GetRelease(), c.GetPreview()
	_, _ = r, p // prevent unused variable
	m.NotAnnotated = 0
	if !(r >= 2) {
		m.Released = 0
	}
	if !(p && r >= 2) {
		m.Previewed = 0
	}
	if !(r < 3 && (r >= 2 || (p && r >= 1))) {
		m.PreviewedReleasedRemoved = 0
	}
}
