// Code generated by protoc-gen-go-torelease. DO NOT EDIT.

package fixtures

import (
	proto_releases "github.com/devnev/proto-releases"
)

func (m *ImportedNotAnnotatedAndEmpty) ToRelease(c *proto_releases.Config) {
}
func (m *ImportedNotAnnotatedWithUnreleasedField) ToRelease(c *proto_releases.Config) {
	if m == nil || c.GetRelease() == 0 {
		return
	}
	m.Released = 0
}
func (m *ImportedNotAnnotatedWithReleasedField) ToRelease(c *proto_releases.Config) {
	if m == nil || c.GetRelease() == 0 {
		return
	}
	r, p := c.GetRelease(), c.GetPreview()
	_, _ = r, p // prevent unused variable
	if !(r >= 2) {
		m.Released = 0
	}
}
func (m *ImportedRelesed) ToRelease(c *proto_releases.Config) {
}
