// Code generated by protoc-gen-baseconvert. DO NOT EDIT.

package testdata

import (
	golden "github.com/devnev/proto-releases/testdata/golden"
)

func (m *EmptyRootMessageReleased) ToBase() *golden.EmptyRootMessageReleased {
	return &golden.EmptyRootMessageReleased{}
}
func (m *EmptyRootMessageReleased) FromBase(b *golden.EmptyRootMessageReleased) {
	m.Reset()
}
func (m *EmptyRootMessagePreviewedThenReleased) ToBase() *golden.EmptyRootMessagePreviewedThenReleased {
	return &golden.EmptyRootMessagePreviewedThenReleased{}
}
func (m *EmptyRootMessagePreviewedThenReleased) FromBase(b *golden.EmptyRootMessagePreviewedThenReleased) {
	m.Reset()
}
func (m *RootMessageNotAnnotated) ToBase() *golden.RootMessageNotAnnotated {
	return &golden.RootMessageNotAnnotated{
		Released:              m.GetReleased(),
		PreviewedThenReleased: m.GetPreviewedThenReleased(),
	}
}
func (m *RootMessageNotAnnotated) FromBase(b *golden.RootMessageNotAnnotated) {
	m.Reset()
	m.Released = b.GetReleased()
	m.PreviewedThenReleased = b.GetPreviewedThenReleased()
}
