// Code generated by protoc-gen-baseconvert. DO NOT EDIT.

package testdata

import (
	golden "github.com/devnev/proto-releases/testdata/golden"
)

func (m *EmptyRootMessageReleased) ToBase() *golden.EmptyRootMessageReleased {
	return &golden.EmptyRootMessageReleased{}
}
func (m *EmptyRootMessageReleased) FromBase(b *golden.EmptyRootMessageReleased) {
	m.Reset()
}
func (m *EmptyRootMessageReleasedEventually) ToBase() *golden.EmptyRootMessageReleasedEventually {
	return &golden.EmptyRootMessageReleasedEventually{}
}
func (m *EmptyRootMessageReleasedEventually) FromBase(b *golden.EmptyRootMessageReleasedEventually) {
	m.Reset()
}
func (m *EmptyRootMessagePreviewed) ToBase() *golden.EmptyRootMessagePreviewed {
	return &golden.EmptyRootMessagePreviewed{}
}
func (m *EmptyRootMessagePreviewed) FromBase(b *golden.EmptyRootMessagePreviewed) {
	m.Reset()
}
func (m *EmptyRootMessagePreviewedThenReleased) ToBase() *golden.EmptyRootMessagePreviewedThenReleased {
	return &golden.EmptyRootMessagePreviewedThenReleased{}
}
func (m *EmptyRootMessagePreviewedThenReleased) FromBase(b *golden.EmptyRootMessagePreviewedThenReleased) {
	m.Reset()
}
func (m *RootMessageNotAnnotated) ToBase() *golden.RootMessageNotAnnotated {
	return &golden.RootMessageNotAnnotated{
		Released:              m.GetReleased(),
		ReleasedEventually:    m.GetReleasedEventually(),
		Previewed:             m.GetPreviewed(),
		PreviewedThenReleased: m.GetPreviewedThenReleased(),
	}
}
func (m *RootMessageNotAnnotated) FromBase(b *golden.RootMessageNotAnnotated) {
	m.Reset()
	m.Released = b.GetReleased()
	m.ReleasedEventually = b.GetReleasedEventually()
	m.Previewed = b.GetPreviewed()
	m.PreviewedThenReleased = b.GetPreviewedThenReleased()
}
