// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: release-option-combinations.proto

package testdata

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestServiceClient interface {
	EmptyMethodNotAnnotated(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	EmptyMethodReleased(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MethodNotAnnotated(ctx context.Context, in *MessageNotAnnotated, opts ...grpc.CallOption) (*MessageNotAnnotated, error)
	MethodReleased(ctx context.Context, in *MessageNotAnnotated, opts ...grpc.CallOption) (*MessageNotAnnotated, error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) EmptyMethodNotAnnotated(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/TestService/EmptyMethodNotAnnotated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) EmptyMethodReleased(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/TestService/EmptyMethodReleased", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) MethodNotAnnotated(ctx context.Context, in *MessageNotAnnotated, opts ...grpc.CallOption) (*MessageNotAnnotated, error) {
	out := new(MessageNotAnnotated)
	err := c.cc.Invoke(ctx, "/TestService/MethodNotAnnotated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) MethodReleased(ctx context.Context, in *MessageNotAnnotated, opts ...grpc.CallOption) (*MessageNotAnnotated, error) {
	out := new(MessageNotAnnotated)
	err := c.cc.Invoke(ctx, "/TestService/MethodReleased", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility
type TestServiceServer interface {
	EmptyMethodNotAnnotated(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	EmptyMethodReleased(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	MethodNotAnnotated(context.Context, *MessageNotAnnotated) (*MessageNotAnnotated, error)
	MethodReleased(context.Context, *MessageNotAnnotated) (*MessageNotAnnotated, error)
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTestServiceServer struct {
}

func (UnimplementedTestServiceServer) EmptyMethodNotAnnotated(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmptyMethodNotAnnotated not implemented")
}
func (UnimplementedTestServiceServer) EmptyMethodReleased(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmptyMethodReleased not implemented")
}
func (UnimplementedTestServiceServer) MethodNotAnnotated(context.Context, *MessageNotAnnotated) (*MessageNotAnnotated, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MethodNotAnnotated not implemented")
}
func (UnimplementedTestServiceServer) MethodReleased(context.Context, *MessageNotAnnotated) (*MessageNotAnnotated, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MethodReleased not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_EmptyMethodNotAnnotated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).EmptyMethodNotAnnotated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TestService/EmptyMethodNotAnnotated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).EmptyMethodNotAnnotated(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_EmptyMethodReleased_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).EmptyMethodReleased(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TestService/EmptyMethodReleased",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).EmptyMethodReleased(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_MethodNotAnnotated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageNotAnnotated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).MethodNotAnnotated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TestService/MethodNotAnnotated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).MethodNotAnnotated(ctx, req.(*MessageNotAnnotated))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_MethodReleased_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageNotAnnotated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).MethodReleased(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TestService/MethodReleased",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).MethodReleased(ctx, req.(*MessageNotAnnotated))
	}
	return interceptor(ctx, in, info, handler)
}

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmptyMethodNotAnnotated",
			Handler:    _TestService_EmptyMethodNotAnnotated_Handler,
		},
		{
			MethodName: "EmptyMethodReleased",
			Handler:    _TestService_EmptyMethodReleased_Handler,
		},
		{
			MethodName: "MethodNotAnnotated",
			Handler:    _TestService_MethodNotAnnotated_Handler,
		},
		{
			MethodName: "MethodReleased",
			Handler:    _TestService_MethodReleased_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "release-option-combinations.proto",
}
