// Code generated by protoc-gen-go-baseconvert. DO NOT EDIT.

package fixtures

import (
	fixtures "github.com/devnev/proto-releases/fixtures"
)

func (m *ImportedNotAnnotatedAndEmpty) ToBase() *fixtures.ImportedNotAnnotatedAndEmpty {
	msg := &fixtures.ImportedNotAnnotatedAndEmpty{}
	return msg
}
func (m *ImportedNotAnnotatedAndEmpty) FromBase(b *fixtures.ImportedNotAnnotatedAndEmpty) *ImportedNotAnnotatedAndEmpty {
	if m != nil {
		m.Reset()
	} else {
		m = new(ImportedNotAnnotatedAndEmpty)
	}
	return m
}
func (m *ImportedNotAnnotatedWithUnreleasedField) ToBase() *fixtures.ImportedNotAnnotatedWithUnreleasedField {
	msg := &fixtures.ImportedNotAnnotatedWithUnreleasedField{
		Released: m.GetReleased(),
	}
	return msg
}
func (m *ImportedNotAnnotatedWithUnreleasedField) FromBase(b *fixtures.ImportedNotAnnotatedWithUnreleasedField) *ImportedNotAnnotatedWithUnreleasedField {
	if m != nil {
		m.Reset()
	} else {
		m = new(ImportedNotAnnotatedWithUnreleasedField)
	}
	m.Released = b.GetReleased()
	return m
}
func (m *ImportedNotAnnotatedWithReleasedField) ToBase() *fixtures.ImportedNotAnnotatedWithReleasedField {
	msg := &fixtures.ImportedNotAnnotatedWithReleasedField{
		Released: m.GetReleased(),
	}
	return msg
}
func (m *ImportedNotAnnotatedWithReleasedField) FromBase(b *fixtures.ImportedNotAnnotatedWithReleasedField) *ImportedNotAnnotatedWithReleasedField {
	if m != nil {
		m.Reset()
	} else {
		m = new(ImportedNotAnnotatedWithReleasedField)
	}
	m.Released = b.GetReleased()
	return m
}
func (m *ImportedRelesed) ToBase() *fixtures.ImportedRelesed {
	msg := &fixtures.ImportedRelesed{}
	return msg
}
func (m *ImportedRelesed) FromBase(b *fixtures.ImportedRelesed) *ImportedRelesed {
	if m != nil {
		m.Reset()
	} else {
		m = new(ImportedRelesed)
	}
	return m
}
