// Code generated by protoc-gen-baseconvert. DO NOT EDIT.

package fixtures

import (
	fixtures "github.com/devnev/proto-releases/fixtures"
)

func (m *ImportedNotAnnotatedAndEmpty) ToBase() *fixtures.ImportedNotAnnotatedAndEmpty {
	msg := &fixtures.ImportedNotAnnotatedAndEmpty{}
	return msg
}
func (m *ImportedNotAnnotatedAndEmpty) FromBase(b *fixtures.ImportedNotAnnotatedAndEmpty) {
	m.Reset()
}
func (m *ImportedNotAnnotatedWithUnreleasedField) ToBase() *fixtures.ImportedNotAnnotatedWithUnreleasedField {
	msg := &fixtures.ImportedNotAnnotatedWithUnreleasedField{
		Released: m.GetReleased(),
	}
	return msg
}
func (m *ImportedNotAnnotatedWithUnreleasedField) FromBase(b *fixtures.ImportedNotAnnotatedWithUnreleasedField) {
	m.Reset()
	m.Released = b.GetReleased()
}
func (m *ImportedNotAnnotatedWithReleasedField) ToBase() *fixtures.ImportedNotAnnotatedWithReleasedField {
	msg := &fixtures.ImportedNotAnnotatedWithReleasedField{
		Released: m.GetReleased(),
	}
	return msg
}
func (m *ImportedNotAnnotatedWithReleasedField) FromBase(b *fixtures.ImportedNotAnnotatedWithReleasedField) {
	m.Reset()
	m.Released = b.GetReleased()
}
