package main

import (
	"flag"
	"fmt"

	releases "github.com/devnev/proto-releases"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

func main() {
	protogen.Options{
		ParamFunc: flag.Set,
	}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	filename := file.GeneratedFilenamePrefix + "_torelease.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-torelease. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, m := range file.Messages {
		generateMessage(g, m)
	}

	return g
}

func generateMessage(g *protogen.GeneratedFile, m *protogen.Message) {
	configIdent := g.QualifiedGoIdent(protogen.GoIdent{
		GoImportPath: "github.com/devnev/proto-releases",
		GoName:       "Config",
	})

	g.P("func (m *", m.GoIdent.GoName, ") ToRelease(c *", configIdent, ") {")
	if len(m.Fields) == 0 {
		g.P("}")
		return
	}
	g.P("if m == nil || c.GetRelease() == 0 { return }")
	if hasReleaseOptions(m) {
		g.P("r, p := c.GetRelease(), c.GetPreview()")
		g.P("_, _ = r, p // prevent unused variable")
	}
	for _, f := range m.Fields {
		if f.Oneof != nil {
			continue
		}
		cond := buildCondition(f)
		if f.Message != nil {
			if cond != "" {
				g.P("if !(", cond, ") {")
				g.P("m.", f.GoName, " = nil")
				g.P("}")
			}
			g.P("m.", f.GoName, ".ToRelease(c)")
		} else {
			if cond != "" {
				g.P("if !(", cond, ") {")
			}
			g.P("m.", f.GoName, " = ", f.Desc.Default())
			if cond != "" {
				g.P("}")
			}
		}
	}
	for _, o := range m.Oneofs {
		g.P("switch o := m.", o.GoName, ".(type) {")
		for _, f := range o.Fields {
			cond := buildCondition(f)
			if f.Message != nil {
				g.P("case *", f.GoIdent, ":")
				if cond != "" {
					g.P("if !(", cond, ") {")
					g.P("m.", o.GoName, " = nil")
					g.P("} else {")
					g.P("o.", f.GoName, ".ToRelease(c)")
					g.P("}")
				} else {
					g.P("o.", f.GoName, ".ToRelease(c)")
				}
			} else if cond != "" {
				g.P("case *", f.GoIdent, ":")
				g.P("if !(", cond, ") {")
				g.P("m.", o.GoName, " = nil")
				g.P("}")
			}
		}
		g.P("default:")
		g.P("_ = o // prevent unused variable")
		g.P("m.", o.GoName, " = nil")
		g.P("}")
	}
	g.P("}")
}

func hasReleaseOptions(m *protogen.Message) bool {
	for _, f := range m.Fields {
		range_, _ := proto.GetExtension(f.Desc.Options(), releases.E_Field).(*releases.Range)
		if range_.GetReleaseIn() > 0 || range_.GetPreviewIn() > 0 {
			return true
		}
	}
	return false
}

func buildCondition(f *protogen.Field) string {
	range_, _ := proto.GetExtension(f.Desc.Options(), releases.E_Field).(*releases.Range)
	var cond string
	if range_.GetReleaseIn() > 0 {
		cond = fmt.Sprintf("r >= %d", range_.GetReleaseIn())
	}
	if range_.GetPreviewIn() > 0 {
		if cond != "" {
			cond += " || "
		}
		cond += fmt.Sprintf("(p && r >= %d)", range_.GetPreviewIn())
	}
	if range_.GetRemoveIn() > 0 && cond != "" {
		cond = fmt.Sprintf("r < %d && (%s)", range_.GetRemoveIn(), cond)
	}
	return cond
}
