name: Build & Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  build:
    name: Generate, Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup protoc
      env:
        PROTOC_VERSION: '3.19.4'
      run: >
        curl -fo protoc.zip -sSL \
          "https://github.com/google/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip";
        mkdir protoc;
        unzip -q protoc.zip -d protoc;
        sudo install -m 755 ./protoc/bin/protoc /usr/local/bin/;
        sudo cp -a ./protoc/include/google /usr/local/include/;
        rm protoc.zip protoc -rf;

    - name: Setup protoc-gen-go
      env:  
        PROTOC_GEN_GO_VERSION: '1.27.1'
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v${PROTOC_GEN_GO_VERSION}

    - name: Generate
      run: go generate -x -v ./...

    - name: Require zero diff
      run: git diff --exit-code

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
